<<<<<<< HEAD
export interface SearchResponse {
  data:       Gif[];
  meta:       Meta;
  pagination: Pagination;
=======
// Generated by https://quicktype.io
export interface SearchResponse {
  data:       Gif[];
  pagination: Pagination;
  meta:       Meta;
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
}

export interface Gif {
  type:                       Type;
  id:                         string;
  url:                        string;
  slug:                       string;
  bitly_gif_url:              string;
  bitly_url:                  string;
  embed_url:                  string;
  username:                   Username;
  source:                     string;
  title:                      string;
  rating:                     Rating;
  content_url:                string;
<<<<<<< HEAD
  source_tld:                 string;
  source_post_url:            string;
  is_sticker:                 number;
  import_datetime:            Date;
=======
  source_tld:                 SourceTLD;
  source_post_url:            string;
  is_sticker:                 number;
  import_datetime:            string;
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
  trending_datetime:          string;
  images:                     Images;
  user:                       User;
  analytics_response_payload: string;
  analytics:                  Analytics;
<<<<<<< HEAD
  alt_text:                   string;
=======
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
}

export interface Analytics {
  onload:  Onclick;
  onclick: Onclick;
  onsent:  Onclick;
}

export interface Onclick {
  url: string;
}

export interface Images {
<<<<<<< HEAD
  original:                 FixedHeight;
=======
  original:                 { [key: string]: string };
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
  downsized:                The480_WStill;
  downsized_large:          The480_WStill;
  downsized_medium:         The480_WStill;
  downsized_small:          DownsizedSmall;
  downsized_still:          The480_WStill;
<<<<<<< HEAD
  fixed_height:             FixedHeight;
  fixed_height_downsampled: FixedHeight;
  fixed_height_small:       FixedHeight;
  fixed_height_small_still: The480_WStill;
  fixed_height_still:       The480_WStill;
  fixed_width:              FixedHeight;
  fixed_width_downsampled:  FixedHeight;
  fixed_width_small:        FixedHeight;
  fixed_width_small_still:  The480_WStill;
  fixed_width_still:        The480_WStill;
  looping:                  Looping;
=======
  fixed_height:             { [key: string]: string };
  fixed_height_downsampled: { [key: string]: string };
  fixed_height_small:       { [key: string]: string };
  fixed_height_small_still: The480_WStill;
  fixed_height_still:       The480_WStill;
  fixed_width:              { [key: string]: string };
  fixed_width_downsampled:  { [key: string]: string };
  fixed_width_small:        { [key: string]: string };
  fixed_width_small_still:  The480_WStill;
  fixed_width_still:        The480_WStill;
  looping:                  { [key: string]: string };
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
  original_still:           The480_WStill;
  original_mp4:             DownsizedSmall;
  preview:                  DownsizedSmall;
  preview_gif:              The480_WStill;
  preview_webp:             The480_WStill;
<<<<<<< HEAD
  "480w_still":             The480_WStill;
  hd?:                      DownsizedSmall;
=======
  hd?:                      DownsizedSmall;
  "480w_still":             The480_WStill;
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
}

export interface The480_WStill {
  height: string;
  width:  string;
  size:   string;
  url:    string;
}

export interface DownsizedSmall {
  height:   string;
  width:    string;
  mp4_size: string;
  mp4:      string;
}

<<<<<<< HEAD
export interface FixedHeight {
  height:    string;
  width:     string;
  size:      string;
  url:       string;
  mp4_size?: string;
  mp4?:      string;
  webp_size: string;
  webp:      string;
  frames?:   string;
  hash?:     string;
}

export interface Looping {
  mp4_size: string;
  mp4:      string;
}

export enum Rating {
  G = "g",
  PG = "pg",
  PG13 = "pg-13",
}

=======
export enum Rating {
  G = "g",
  PG13 = "pg-13",
}

export enum SourceTLD {
  Empty = "",
  WWWTwitchTv = "www.twitch.tv",
  WWWYoutubeCOM = "www.youtube.com",
}

>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
export enum Type {
  GIF = "gif",
}

export interface User {
  avatar_url:    string;
  banner_image:  string;
  banner_url:    string;
  profile_url:   string;
  username:      Username;
  display_name:  DisplayName;
  description:   string;
  instagram_url: string;
  website_url:   string;
  is_verified:   boolean;
}

export enum DisplayName {
<<<<<<< HEAD
  Valorant = "VALORANT",
  Xbox = "Xbox",
}

export enum Username {
  Playvalorant = "playvalorant",
  Xbox = "xbox",
=======
  Nyxl = "NYXL",
  VALORANTEsports = "VALORANT Esports",
  Valorant = "VALORANT",
}

export enum Username {
  Andbox = "andbox",
  Playvalorant = "playvalorant",
  ValorantEsports = "Valorant_Esports",
>>>>>>> caf7d66d2559c6de6e4f0cf73c809038106d6d89
}

export interface Meta {
  status:      number;
  msg:         string;
  response_id: string;
}

export interface Pagination {
  total_count: number;
  count:       number;
  offset:      number;
}
